### ISSUE TITLE
Unit testing for `user.rs`

### ISSUE THREAD

**Issue by calejvaldez** [ojosproject/iris#7]
### Summary

Make sure to finish `user.rs` and create unit tests.

### Tasks

- [ ] Finish `User.py`
- [ ] Ensure it interacts properly with the `DB` constant imported from `main.py`
- [ ] Try to get as much code coverage as possible

**Comment by calejvaldez** [comment]
Ongoing, will continue to stay ongoing, don't think it should remain as an issue.
